### ISSUE TITLE
[feat] Domain Layer 설계

### ISSUE THREAD

**Issue by wongbingg** [wongbingg/BoxOffice2#1]
## Description 
프로젝트에 필요한 Domain Layer를 설계한다.

## TODO
- [x] Domain 그룹 생성
- [x] Domain 그룹 내 Entities 그룹 생성
- [x] Domain 그룹 내 UseCases 그룹 생성
- [x] Domain 그룹 내 Interfaces 그룹 생성
